### ISSUE TITLE
xraylib version

### ISSUE THREAD

**Issue by woutdenolf** [golosio/xrmc#40]
configure.ac requires xraylib version 3.99.0. I assume this is a typo?

**Comment by tschoonj** [comment]
No it's not: see [this comment](https://github.com/golosio/xrmc/commit/457f744ab7f6d8275079b620818e2363f512f235#commitcomment-33193914)

**Comment by woutdenolf** [comment]
My bad, I forgot to link with respect to the xraylib master build.
