### ISSUE TITLE
XRMC XMI-MSIM plug in detectorconvolute Ascii Flag not working

### ISSUE THREAD

**Issue by edboj** [golosio/xrmc#50]
Greetings,

When using the AsciiFlag on detectorconvolute that inherits detectorarray, an syntax error occur indicating that the flag does not work.
I wish to save the results as ASCII to see the simulated spectrum. Is there another way to do this without using the AsciiFlag?
`Newdevice detectorconvolute 	; Device type`
`Detector                   	; Device name`
`...`
`AsciiFlag 1                    ;  Use Ascii format in output file (0/1)`

Thanks!

**Comment by tschoonj** [comment]
Hi @edboj !

That flag is indeed not supported.

Instead, I recommend you install the python part of the [xrmc-utils](https://github.com/tschoonj/xrmc-utils/tree/master/python), which should make visualising the binary outputfiles easy, and also allow you to convert them to csv.

Hope this helps!

**Comment by edboj** [comment]
Hello @tschoonj ,

The [xrmc-utils](https://github.com/tschoonj/xrmc-utils/tree/master/python) worked perfectly, it helped me a lot.

Thank you very much for the quick support!

**Comment by tschoonj** [comment]
You're welcome. Let us know if you have any more questions.
